version: '3.9'

services:
  app:
    build: .
    restart: always
    ports: 
    - 80:8080
    depends_on:
      - psqldb
    networks:
      back:
  psqldb:
    image: postgres:13
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql
    environment: 
      POSTGRES_PASSWORD: example
      POSTGRES_USER: keshox
      POSTGRES_DB: spring
    networks:
      back:

networks:
  back:
    
